# Generated by Django 2.1.7 on 2019-03-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='data_adicionado',
            field=models.DateField(auto_now_add=True, default='1900-01-01'),
            preserve_default=False,
        ),
    ]
