# Generated by Django 2.1.7 on 2019-03-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0002_etiqueta_data_adicionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='data_adicionado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
