# Generated by Django 2.1.7 on 2019-03-11 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0003_auto_20190311_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='data_gerado',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
