# Generated by Django 2.1.7 on 2019-03-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0005_auto_20190311_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('orgao', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('data_gerado', models.DateTimeField(null=True)),
                ('id_destinatario', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rementente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('orgao', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
    ]
