# Generated by Django 2.1.7 on 2019-03-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0007_auto_20190313_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rementente',
            new_name='Remetente',
        ),
        migrations.RenameField(
            model_name='destinatario',
            old_name='id_rementente',
            new_name='id_remetente',
        ),
    ]
