# Generated by Django 2.1.7 on 2019-03-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0009_auto_20190320_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinatario',
            old_name='id_remetente',
            new_name='remetente',
        ),
    ]
